version: '3.8'

services:
  wiremock:
    image: wiremock/wiremock:3.5.2
    container_name: wiremock-server
    ports:
      - "9999:9999"
    volumes:
      - ./mappings:/home/wiremock/mappings
      - ./__files:/home/wiremock/__files
    command: --port 9999 --verbose
